### ISSUE TITLE
support EventBridge scheduler

### ISSUE THREAD

**Issue by ryo-murai** [alarm-craft/alarm-craft#6]
# Target resource type and alarm dimension
|Service|Resource|[target_resource_type](Configuration#definitions%2Fresource_config)|Namespace|Dimensions|
|-|-|-|-|-|
|EventBridge Scheduler|Schedule Group|`"scheduler:schedule-group"`|AWS/Scheduler|[`ScheduleGroup`](https://docs.aws.amazon.com/scheduler/latest/UserGuide/monitoring-cloudwatch.html#monitoring-cloudwatch-dimensions)|

# API to retrieve target resources
* resourcegroupstaggingapi

# TODO
- [x] Add Provider class
- [x] Add test data in `_test_params()` of `test_target_metrics_provider_rgta.py`
- [x] Add enum value in target_resource_type in config_schema.json, then generate docs
- [x] Add sample for this resource_type in config-sample.yaml

# Notes
* None
